version: '3'
services: 
  redis-server:
    image: "redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - "6379"
  node-app:
    restart: unless-stopped
    build: .
    ports:
    #First port is local machine : conatiner port
      - "4001:8081"